### ISSUE TITLE
Implement Jazzband guidelines for prettytable

### ISSUE THREAD

**Issue by hugovk** [prettytable/prettytable#22]
This issue tracks the implementation of the [Jazzband guidelines](https://jazzband.co/about/guidelines) for the project [prettytable](https://github.com/jazzband/prettytable).

See the [TODO list](#todos) below for the generally required tasks, but feel free to update it in case the project requires it.

(Based on the list at https://github.com/jazzband/tablib/issues/378.)

Feel free to ping a [Jazzband roadie](https://jazzband.co/roadies) if you have any question.

## TODOs<a name="todos"></a>

- [x] Fix all links in the docs (and README file etc) from old to new repo
- [x] Add the [Jazzband badge](https://jazzband.co/about/guidelines#badges) to the `README` file -> https://github.com/jazzband/prettytable/pull/20
- [x] Add the [Jazzband contributing guideline](https://jazzband.co/about/guidelines#contributing-guidelines) to the `CONTRIBUTING.md` or `CONTRIBUTING.rst` file
- [x] Check if continuous testing works (e.g. [Travis-CI](https://travis-ci.org/), [CircleCI](https://circleci.com), [AppVeyor](https://www.appveyor.com), etc) -> https://travis-ci.org/jazzband/prettytable
- [x] Check if test coverage services work (e.g. [Coveralls](https://coveralls.io), [Codecov](https://codecov.io), etc) -> https://codecov.io/gh/jazzband/prettytable
- [x] Add `jazzband` account to [PyPI](https://pypi.org/) project as maintainer role (e.g. URL: https://pypi.org/manage/project/prettytable/collaboration/)
- [n/a] Add `jazzband-bot` as maintainer to the [Read the Docs](https://readthedocs.org/) project (e.g. URL: https://readthedocs.org/dashboard/prettytable/users/)
- [n/a] Add incoming GitHub webhook integration to Read the Docs project (e.g. URL: https://readthedocs.org/dashboard/prettytable/integrations/)
- [x] Fix project URL in [GitHub project](https://github.com/jazzband/prettytable) description -> No URL
- [n/a] Review project if other services are used and port them to Jazzband -> there's a Fussy Fox integration that's not set up: https://github.com/jazzband/prettytable/runs/188061304. I've not used this service before, do we need it here?
- [x] Decide who is project lead for the project (if at all)
- [x] Set up CI for Jazzband project releases if needed and open ticket if yes

**Comment by hugovk** [comment]
I've updated all those I'm able to.

Ping @flaper87 and @jezdez for the others.

**Comment by flaper87** [comment]
`prettytable` has not been published on RTD yet so the whole setup should be done from scratch. I've given `jazzband` permissions on pypi and we should be able to automate releases.

**Comment by hugovk** [comment]
I've marked the RTD tasks as `[n/a]` because there is no RTD yet, and created https://github.com/jazzband/prettytable/issues/25 to import the old docs from the Google Code Archive wiki. If we need RTD in the future, we can set it up. Not a blocker.

I've also marked the "other services" one as `[n/a]`, as the Fussy Fox thing doesn't seem essential right now, and not a blocker. We can deal with it later if needed.

@jezdez Please can you: "set up CI for Jazzband project releases if needed and open ticket if yes"?

When ready, I'd like to make a new release soon. I'll post a plan in https://github.com/jazzband/prettytable/issues/18.

**Comment by hugovk** [comment]
I've posted a request for help at https://github.com/jazzband-roadies/help/issues/202. If nothing happens, another option to consider is a [PEP 541 transfer](https://www.python.org/dev/peps/pep-0541/).

**Comment by jezdez** [comment]
To enable the Jazzband releases we need to have a project lead first, so they can confirm releases pushed to the Jazzband package index. @hugovk Do you want to be project lead?

**Comment by hugovk** [comment]
@jezdez Sure, I can do that, at least to get a few new releases out the door. Thanks!

**Comment by hugovk** [comment]
Also, not sure if @flaper87 is interested at this time, but as a courtesy, would you @flaper87 also like to be a project lead?

**Comment by flaper87** [comment]
> Also, not sure if @flaper87 is interested at this time, but as a courtesy, would you @flaper87 also like to be a project lead?

It would not be responsible for me to sign up to maintain this project knowing my current availability. I'm not actively working on this project anymore. I don't mind being around but I'd rather not be the Project Lead or main point of contact :hugs:

**Comment by jezdez** [comment]
I'm just going to assume it'll be @hugovk only for now, but the roadies (me at the moment) will get release mails as well and can act as fallbacks. Better would be multiple leads of course, but that's a situations that some projects simply aren't in.

**Comment by jezdez** [comment]
This is done now. 🎊
